import { addDays } from "date-fns"
import { ToolStatus } from "~/.generated/prisma/client"
import { db } from "~/services/db"

const ADMIN_EMAIL = "admin@adspotfinder.com"

const DUMMY_CONTENT = `This platform offers excellent advertising opportunities for startups, SaaS products, and indie makers. With a **highly engaged audience** of founders, developers, and entrepreneurs, it provides targeted exposure that drives meaningful traffic and conversions. Whether you're launching a new product or scaling an existing one, advertising here connects you directly with decision-makers and early adopters.

The site features **flexible ad formats** including sidebar banners, newsletter sponsorships, dedicated spots, and featured listings. Many platforms in this space have high Domain Authority (DA 50+), strong organic traffic, and a focused niche audience interested in tools, products, and services. Sponsorships often include detailed analytics, allowing you to track clicks, sign-ups, and ROI effectively.

Getting started is simple—most sites have clear media kits with pricing, audience demographics, and past performance data. The community values authentic promotions, leading to higher engagement rates compared to general advertising channels. Regular sponsorships can build brand recognition and foster long-term partnerships within the ecosystem.`

async function main() {
  const now = new Date()

  console.log("Starting third batch ad spots seeding (50 new ones from yo.directory and popular sources)...")

  const additionalPlatformsBatch3 = [
    {
      name: "Startups.Gallery",
      slug: "startups-gallery",
      websiteUrl: "https://startups.gallery",
      tagline: "Monochromatic startup discovery directory",
      description: "Curated directory of startups with submission options and newsletter sponsorships.",
      isFeatured: true,
      status: ToolStatus.Published,
      publishedAt: now,
      screenshotUrl: "",
      categories: ["directories"],
      tags: ["paid-promotion", "newsletter-ads", "startups"],
    },
    {
      name: "Productivity.Directory",
      slug: "productivity-directory",
      websiteUrl: "https://productivity.directory",
      tagline: "Directory of productivity tools",
      description: "Focused on productivity apps with ads, newsletter, and paid submission sponsorships.",
      status: ToolStatus.Published,
      publishedAt: now,
      screenshotUrl: "",
      categories: ["directories"],
      tags: ["paid-promotion", "newsletter-ads", "indie-makers"],
    },
    {
      name: "Startup Fame",
      slug: "startup-fame",
      websiteUrl: "https://startupfame.co", // Common URL based on mentions
      tagline: "Trending startups directory",
      description: "Showcases trending startups with ads and submission sponsorship opportunities.",
      status: ToolStatus.Published,
      publishedAt: now,
      screenshotUrl: "",
      categories: ["directories", "launch-platforms"],
      tags: ["paid-promotion", "startups"],
    },
    {
      name: "Growstartup",
      slug: "growstartup",
      websiteUrl: "https://growstartup.co",
      tagline: "Directories to submit your startup",
      description: "Meta-directory of 300+ places to launch with sponsorship options.",
      status: ToolStatus.Published,
      publishedAt: now,
      screenshotUrl: "",
      categories: ["marketplaces"],
      tags: ["sponsorships", "startups"],
    },
    {
      name: "Dang.ai",
      slug: "dang-ai",
      websiteUrl: "https://dang.ai",
      tagline: "AI tools directory",
      description: "Directory for AI products with submissions and newsletter sponsorships.",
      status: ToolStatus.Published,
      publishedAt: now,
      screenshotUrl: "",
      categories: ["directories"],
      tags: ["newsletter-ads", "paid-promotion"],
    },
    {
      name: "Hayo AI",
      slug: "hayo-ai",
      websiteUrl: "https://hayo.com",
      tagline: "Artificial intelligence tools directory",
      description: "Large AI directory offering newsletter sponsorship opportunities.",
      status: ToolStatus.Published,
      publishedAt: now,
      screenshotUrl: "",
      categories: ["directories"],
      tags: ["newsletter-ads", "high-da"],
    },
    {
      name: "Seesaw Website",
      slug: "seesaw-website",
      websiteUrl: "https://seesaw.website",
      tagline: "Web design inspiration directory",
      description: "Inspiration gallery with submissions and newsletter sponsorships.",
      status: ToolStatus.Published,
      publishedAt: now,
      screenshotUrl: "",
      categories: ["directories"],
      tags: ["newsletter-ads", "indie-makers"],
    },
    {
      name: "ToolFinder",
      slug: "toolfinder",
      websiteUrl: "https://toolfinder.co",
      tagline: "Software discovery directory",
      description: "Curated tools directory popular for submissions and promotions.",
      status: ToolStatus.Published,
      publishedAt: now,
      screenshotUrl: "",
      categories: ["directories"],
      tags: ["paid-promotion"],
    },
    {
      name: "LaunchVault",
      slug: "launchvault",
      websiteUrl: "https://launchvault.dev",
      tagline: "Product launch platform for startups",
      description: "Dedicated launch platform with paid features for visibility.",
      status: ToolStatus.Published,
      publishedAt: now,
      screenshotUrl: "",
      categories: ["launch-platforms"],
      tags: ["product-launch", "startups"],
    },
    {
      name: "DevHub Best",
      slug: "devhub-best",
      websiteUrl: "https://devhub.best",
      tagline: "Startup directory",
      description: "Directory focused on developer and startup tools with promotion options.",
      status: ToolStatus.Published,
      publishedAt: now,
      screenshotUrl: "",
      categories: ["directories"],
      tags: ["startups"],
    },
    {
      name: "SaaSHunt Best",
      slug: "saashunt-best",
      websiteUrl: "https://saashunt.best",
      tagline: "SaaS directory",
      description: "Curated SaaS listings with paid and featured opportunities.",
      status: ToolStatus.Published,
      publishedAt: now,
      screenshotUrl: "",
      categories: ["directories"],
      tags: ["saas", "paid-promotion"],
    },
    {
      name: "Go Publicly",
      slug: "go-publicly",
      websiteUrl: "https://go-publicly.com",
      tagline: "Product Hunt alternative directory",
      description: "Alternative launch and directory site for indie products.",
      status: ToolStatus.Published,
      publishedAt: now,
      screenshotUrl: "",
      categories: ["launch-platforms", "directories"],
      tags: ["product-launch"],
    },
    {
      name: "LaunchIgniter",
      slug: "launchigniter",
      websiteUrl: "https://launchigniter.com",
      tagline: "SaaS product directory",
      description: "Directory for launching and promoting SaaS products.",
      status: ToolStatus.Published,
      publishedAt: now,
      screenshotUrl: "",
      categories: ["directories"],
      tags: ["saas"],
    },
    {
      name: "KillerStartups",
      slug: "killerstartups",
      websiteUrl: "https://www.killerstartups.com",
      tagline: "Internet entrepreneurs directory",
      description: "Long-established startup showcase with submission and ad options.",
      status: ToolStatus.Published,
      publishedAt: now,
      screenshotUrl: "https://www.killerstartups.com/wp-content/uploads/2020/08/og-image.jpg",
      categories: ["directories"],
      tags: ["startups", "high-da"],
    },
    {
      name: "StartupBuffer",
      slug: "startupbuffer",
      websiteUrl: "https://startupbuffer.com",
      tagline: "Premium startup directory",
      description: "Paid submissions with multi-channel exposure for launches.",
      isFeatured: true,
      status: ToolStatus.Published,
      publishedAt: now,
      screenshotUrl: "https://startupbuffer.com/assets/og-image.png",
      categories: ["directories", "launch-platforms"],
      tags: ["paid-promotion"],
    },
    {
      name: "TinyStartups",
      slug: "tinystartups",
      websiteUrl: "https://tinystartups.com", // Assumed active variant
      tagline: "Micro startups directory",
      description: "Directory of small/indie startups with newsletter and ads.",
      status: ToolStatus.Published,
      publishedAt: now,
      screenshotUrl: "",
      categories: ["directories"],
      tags: ["indie-makers"],
    },
    {
      name: "StartupBase",
      slug: "startupbase",
      websiteUrl: "https://startupbase.io",
      tagline: "Startup product directory",
      description: "Community-driven directory with submissions and promotions.",
      status: ToolStatus.Published,
      publishedAt: now,
      screenshotUrl: "",
      categories: ["directories"],
      tags: ["startups"],
    },
    {
      name: "Logggos Club",
      slug: "logggos-club",
      websiteUrl: "https://logggos.club",
      tagline: "Logo inspiration directory",
      description: "Logo gallery with submission sponsorship opportunities.",
      status: ToolStatus.Published,
      publishedAt: now,
      screenshotUrl: "",
      categories: ["directories"],
      tags: ["paid-promotion"],
    },
    {
      name: "BestAI.pro",
      slug: "bestai-pro",
      websiteUrl: "https://bestai.pro",
      tagline: "Greatest AI tools database",
      description: "Large AI directory with potential sponsorships.",
      status: ToolStatus.Published,
      publishedAt: now,
      screenshotUrl: "",
      categories: ["directories"],
      tags: ["saas"],
    },
    {
      name: "NocodeFinder",
      slug: "nocodefinder",
      websiteUrl: "https://nocodefinder.com",
      tagline: "No-code tools directory",
      description: "Curated no-code resources with promotion options.",
      status: ToolStatus.Published,
      publishedAt: now,
      screenshotUrl: "",
      categories: ["directories"],
      tags: ["indie-makers"],
    },
    {
      name: "ToolRain",
      slug: "toolrain",
      websiteUrl: "https://toolrain.com",
      tagline: "AI tools directory",
      description: "Comprehensive AI tool listings with ad potential.",
      status: ToolStatus.Published,
      publishedAt: now,
      screenshotUrl: "",
      categories: ["directories"],
      tags: ["paid-promotion"],
    },
    {
      name: "SaaSFrame",
      slug: "saasframe",
      websiteUrl: "https://www.saasframe.io",
      tagline: "SaaS screenshots gallery",
      description: "Inspiration gallery with featured promotion slots.",
      status: ToolStatus.Published,
      publishedAt: now,
      screenshotUrl: "",
      categories: ["directories"],
      tags: ["saas"],
    },
    {
      name: "Marketer Milk Newsletter",
      slug: "marketer-milk",
      websiteUrl: "https://www.marketermilk.com",
      tagline: "Newsletter for marketers and founders",
      description: "Growth-focused newsletter with sponsorship slots.",
      status: ToolStatus.Published,
      publishedAt: now,
      screenshotUrl: "",
      categories: ["newsletters"],
      tags: ["newsletter-ads", "startups"],
    },
    {
      name: "The Bootstrapped Founder Newsletter",
      slug: "bootstrapped-founder-newsletter",
      websiteUrl: "https://thebootstrappedfounder.com",
      tagline: "Newsletter for bootstrappers",
      description: "Influential indie newsletter offering sponsorships.",
      status: ToolStatus.Published,
      publishedAt: now,
      screenshotUrl: "",
      categories: ["newsletters"],
      tags: ["newsletter-ads", "indie-makers"],
    },
    {
      name: "Dense Discovery Newsletter",
      slug: "dense-discovery",
      websiteUrl: "https://densediscovery.com",
      tagline: "Curated design and tech newsletter",
      description: "High-quality newsletter with sponsorship opportunities.",
      status: ToolStatus.Published,
      publishedAt: now,
      screenshotUrl: "https://densediscovery.com/og-image.jpg",
      categories: ["newsletters"],
      tags: ["newsletter-ads"],
    },
    {
      name: "Daily.dev",
      slug: "daily-dev",
      websiteUrl: "https://daily.dev",
      tagline: "Developer news feed with ads",
      description: "Personalized dev platform with sponsorship options.",
      status: ToolStatus.Published,
      publishedAt: now,
      screenshotUrl: "https://daily.dev/og-image.png",
      categories: ["communities", "newsletters"],
      tags: ["newsletter-ads"],
    },
    {
      name: "SaaS Mantra",
      slug: "saas-mantra",
      websiteUrl: "https://saasmantra.com",
      tagline: "Lifetime deals community",
      description: "Deal platform with promotional partnerships.",
      status: ToolStatus.Published,
      publishedAt: now,
      screenshotUrl: "",
      categories: ["marketplaces"],
      tags: ["saas", "paid-promotion"],
    },
    {
      name: "Dealify",
      slug: "dealify",
      websiteUrl: "https://dealify.com",
      tagline: "Lifetime deals for growth",
      description: "Popular deals site for SaaS promotions.",
      status: ToolStatus.Published,
      publishedAt: now,
      screenshotUrl: "https://dealify.com/og-image.jpg",
      categories: ["marketplaces"],
      tags: ["saas", "paid-promotion"],
    },
    {
      name: "Founders Database",
      slug: "founders-database",
      websiteUrl: "https://foundersdatabase.com",
      tagline: "Bootstrapped founders directory",
      description: "Directory with newsletter and ad opportunities.",
      status: ToolStatus.Published,
      publishedAt: now,
      screenshotUrl: "",
      categories: ["directories"],
      tags: ["indie-makers"],
    },
    {
      name: "StartupTile",
      slug: "startuptile",
      websiteUrl: "https://startuptile.com",
      tagline: "Aggregated startup launches",
      description: "Collects launches from multiple platforms with promotions.",
      status: ToolStatus.Published,
      publishedAt: now,
      screenshotUrl: "",
      categories: ["directories"],
      tags: ["product-launch"],
    },
    {
      name: "SiteInspire",
      slug: "siteinspire",
      websiteUrl: "https://siteinspire.com",
      tagline: "Web design showcase directory",
      description: "Premium design inspiration with submission options.",
      status: ToolStatus.Published,
      publishedAt: now,
      screenshotUrl: "",
      categories: ["directories"],
      tags: ["high-da"],
    },
    {
      name: "StartupAITools",
      slug: "startupaitools",
      websiteUrl: "https://startupaitools.com",
      tagline: "Startup AI tools directory",
      description: "Focused AI directory for startups with ads.",
      status: ToolStatus.Published,
      publishedAt: now,
      screenshotUrl: "",
      categories: ["directories"],
      tags: ["saas"],
    },
    {
      name: "DirectoryScout",
      slug: "directoryscout",
      websiteUrl: "https://directoryscout.com",
      tagline: "Directory software and templates",
      description: "Meta resource with promotion potential.",
      status: ToolStatus.Published,
      publishedAt: now,
      screenshotUrl: "",
      categories: ["marketplaces"],
      tags: ["sponsorships"],
    },
    {
      name: "DesiFounder",
      slug: "desifounder",
      websiteUrl: "https://desifounder.com",
      tagline: "Startup launchpad directory",
      description: "Regional-focused startup directory with submissions.",
      status: ToolStatus.Published,
      publishedAt: now,
      screenshotUrl: "",
      categories: ["directories"],
      tags: ["startups"],
    },
    {
      name: "KnowFounder",
      slug: "knowfounder",
      websiteUrl: "https://knowfounder.online",
      tagline: "Product-based startups directory",
      description: "Curated product startup listings.",
      status: ToolStatus.Published,
      publishedAt: now,
      screenshotUrl: "",
      categories: ["directories"],
      tags: ["startups"],
    },
    {
      name: "ListedAI",
      slug: "listedai",
      websiteUrl: "https://listedai.co",
      tagline: "AI software directory",
      description: "AI-focused directory with promotion options.",
      status: ToolStatus.Published,
      publishedAt: now,
      screenshotUrl: "",
      categories: ["directories"],
      tags: ["paid-promotion"],
    },
    {
      name: "HustleFinder",
      slug: "hustlefinder",
      websiteUrl: "https://hustlefinder.com",
      tagline: "Side hustle directory",
      description: "Directory for side projects and hustles.",
      status: ToolStatus.Published,
      publishedAt: now,
      screenshotUrl: "",
      categories: ["directories"],
      tags: ["indie-makers"],
    },
    {
      name: "RankMyAI",
      slug: "rankmyai",
      websiteUrl: "https://rankmyai.com",
      tagline: "AI tools directory",
      description: "Ranked AI listings with sponsorship potential.",
      status: ToolStatus.Published,
      publishedAt: now,
      screenshotUrl: "",
      categories: ["directories"],
      tags: ["saas"],
    },
    {
      name: "AddAI Directory",
      slug: "addaidirectory",
      websiteUrl: "https://addaidirectory.com",
      tagline: "AI agent directory",
      description: "Specialized AI agents showcase.",
      status: ToolStatus.Published,
      publishedAt: now,
      screenshotUrl: "",
      categories: ["directories"],
      tags: ["paid-promotion"],
    },
    {
      name: "Digitool",
      slug: "digitool",
      websiteUrl: "https://digitool.co",
      tagline: "Digital tools directory",
      description: "Broad digital tool listings.",
      status: ToolStatus.Published,
      publishedAt: now,
      screenshotUrl: "",
      categories: ["directories"],
      tags: ["startups"],
    },
    {
      name: "Rilna",
      slug: "rilna",
      websiteUrl: "https://rilna.net",
      tagline: "SaaS for small businesses",
      description: "Niche SaaS directory.",
      status: ToolStatus.Published,
      publishedAt: now,
      screenshotUrl: "",
      categories: ["directories"],
      tags: ["saas"],
    },
    {
      name: "AIToolzDir",
      slug: "aitoolzdir",
      websiteUrl: "https://aitoolzdir.com",
      tagline: "AI tools directory",
      description: "Another AI-focused promotion spot.",
      status: ToolStatus.Published,
      publishedAt: now,
      screenshotUrl: "",
      categories: ["directories"],
      tags: ["paid-promotion"],
    },
    {
      name: "AgentWise",
      slug: "agentwise",
      websiteUrl: "https://agentwise.org",
      tagline: "AI directory",
      description: "General AI resource directory.",
      status: ToolStatus.Published,
      publishedAt: now,
      screenshotUrl: "",
      categories: ["directories"],
      tags: ["saas"],
    },
    {
      name: "AgentHunter",
      slug: "agenthunter",
      websiteUrl: "https://agenthunter.io",
      tagline: "AI agents directory",
      description: "Specialized agents listings.",
      status: ToolStatus.Published,
      publishedAt: now,
      screenshotUrl: "",
      categories: ["directories"],
      tags: ["indie-makers"],
    },
    {
      name: "Altern.ai",
      slug: "altern-ai",
      websiteUrl: "https://altern.ai",
      tagline: "AI directory",
      description: "Alternative AI tools showcase.",
      status: ToolStatus.Published,
      publishedAt: now,
      screenshotUrl: "",
      categories: ["directories"],
      tags: ["paid-promotion"],
    },
    {
      name: "RevTable",
      slug: "revtable",
      websiteUrl: "https://revtable.com",
      tagline: "RevTech tools directory",
      description: "Revenue technology focused.",
      status: ToolStatus.Scheduled,
      publishedAt: addDays(now, 3),
      screenshotUrl: "",
      categories: ["directories"],
      tags: ["saas"],
    },
    {
      name: "TopSocialTools",
      slug: "topsocialtools",
      websiteUrl: "https://topsocialtools.com",
      tagline: "Social media tools directory",
      description: "Marketing tools directory.",
      status: ToolStatus.Published,
      publishedAt: now,
      screenshotUrl: "",
      categories: ["directories"],
      tags: ["paid-promotion"],
    },
    {
      name: "FindTopAITools",
      slug: "findtopaitools",
      websiteUrl: "https://findtopaitools.com",
      tagline: "Top AI tools directory",
      description: "Curated top AI listings.",
      status: ToolStatus.Published,
      publishedAt: now,
      screenshotUrl: "",
      categories: ["directories"],
      tags: ["saas"],
    },
    {
      name: "AIAgentStore",
      slug: "aiagentstore",
      websiteUrl: "https://aiagentstore.ai",
      tagline: "AI agents directory",
      description: "Store-like AI agent promotions.",
      status: ToolStatus.Draft,
      screenshotUrl: "",
      categories: ["directories"],
      tags: ["indie-makers"],
      owner: { connect: { email: ADMIN_EMAIL } },
    },
    {
      name: "SaaSBoilerplates",
      slug: "saasboilerplates",
      websiteUrl: "https://saasboilerplates.dev",
      tagline: "SaaS boilerplates directory",
      description: "Resources for SaaS builders.",
      status: ToolStatus.Draft,
      screenshotUrl: "",
      categories: ["directories"],
      tags: ["saas"],
      owner: { connect: { email: ADMIN_EMAIL } },
    },
  ]

  // Exactly the same loop pattern as previous seeds
  for (const { categories, tags, ...platformData } of additionalPlatformsBatch3) {
    await db.tool.create({
      data: {
        ...platformData,
        content: DUMMY_CONTENT,
        faviconUrl: `https://www.google.com/s2/favicons?sz=128&domain_url=${platformData.websiteUrl}`,
        categories: { connect: categories.map(slug => ({ slug })) },
        tags: { connect: tags.map(slug => ({ slug })) },
      },
    })
  }

  console.log("Added 50 new ad spot platforms (focused on yo.directory listings and popular directories)")
  console.log("Third batch seeding completed!")
}

main()
  .catch(e => {
    console.error("Error during third batch seeding:", e)
    process.exit(1)
  })
  .finally(async () => {
    await db.$disconnect()
  })